apiVersion: v1
kind: Service
metadata:
  name: #NAME
  labels:
    app: #NAME
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: #NAME
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: #NAME
spec:
  replicas: 1
  selector:
    matchLabels:
      app: #NAME
  template:
    metadata:
      labels:
        app: #NAME
    spec:
      containers:
        - name: #NAME
          image: #REPOSITORY
          imagePullPolicy: Always
          command: [
            "./app",
          ]
          env:
            - name: VERSION
              value: #VERSION
            - name: MONGODB_HOSTS
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: MONGODB_HOSTS
            - name: MONGODB_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: MONGODB_USERNAME
            - name: MONGODB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: MONGODB_PASSWORD
            - name: MONGODB_DATABASE
              value: #NAME
            - name: NATS_HOST
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: NATS_HOST
            - name: NATS_USER
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: NATS_USER
            - name: NATS_PASS
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: NATS_PASS
            - name: SENTRY_HOST
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: SENTRY_HOST
            - name: ENVIRONMENT
              valueFrom:
                configMapKeyRef:
                  name: application
                  key: ENVIRONMENT
          ports:
            - containerPort: 80
              name: port
      imagePullSecrets:
        - name: regcred
