// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api/proto/trading.proto

package tradingAPI

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Status int32

const (
	Status_OK           Status = 0
	Status_NOT_FOUND    Status = 1
	Status_INVALID_DATA Status = 2
	Status_SERVER_ERROR Status = 3
)

var Status_name = map[int32]string{
	0: "OK",
	1: "NOT_FOUND",
	2: "INVALID_DATA",
	3: "SERVER_ERROR",
}

var Status_value = map[string]int32{
	"OK":           0,
	"NOT_FOUND":    1,
	"INVALID_DATA": 2,
	"SERVER_ERROR": 3,
}

func (x Status) String() string {
	return proto.EnumName(Status_name, int32(x))
}

func (Status) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{0}
}

type BalanceRequest struct {
	AccountIds           []string `protobuf:"bytes,1,rep,name=accountIds,proto3" json:"accountIds,omitempty"`
	Names                []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	Exchanges            []string `protobuf:"bytes,3,rep,name=exchanges,proto3" json:"exchanges,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BalanceRequest) Reset()         { *m = BalanceRequest{} }
func (m *BalanceRequest) String() string { return proto.CompactTextString(m) }
func (*BalanceRequest) ProtoMessage()    {}
func (*BalanceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{0}
}

func (m *BalanceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceRequest.Unmarshal(m, b)
}
func (m *BalanceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceRequest.Marshal(b, m, deterministic)
}
func (m *BalanceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceRequest.Merge(m, src)
}
func (m *BalanceRequest) XXX_Size() int {
	return xxx_messageInfo_BalanceRequest.Size(m)
}
func (m *BalanceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceRequest proto.InternalMessageInfo

func (m *BalanceRequest) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

func (m *BalanceRequest) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *BalanceRequest) GetExchanges() []string {
	if m != nil {
		return m.Exchanges
	}
	return nil
}

type BalanceResponse struct {
	Balance              *Balance   `protobuf:"bytes,1,opt,name=balance,proto3" json:"balance,omitempty"`
	Balances             []*Balance `protobuf:"bytes,2,rep,name=balances,proto3" json:"balances,omitempty"`
	Status               Status     `protobuf:"varint,3,opt,name=status,proto3,enum=tradingAPI.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *BalanceResponse) Reset()         { *m = BalanceResponse{} }
func (m *BalanceResponse) String() string { return proto.CompactTextString(m) }
func (*BalanceResponse) ProtoMessage()    {}
func (*BalanceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{1}
}

func (m *BalanceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BalanceResponse.Unmarshal(m, b)
}
func (m *BalanceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BalanceResponse.Marshal(b, m, deterministic)
}
func (m *BalanceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BalanceResponse.Merge(m, src)
}
func (m *BalanceResponse) XXX_Size() int {
	return xxx_messageInfo_BalanceResponse.Size(m)
}
func (m *BalanceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BalanceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BalanceResponse proto.InternalMessageInfo

func (m *BalanceResponse) GetBalance() *Balance {
	if m != nil {
		return m.Balance
	}
	return nil
}

func (m *BalanceResponse) GetBalances() []*Balance {
	if m != nil {
		return m.Balances
	}
	return nil
}

func (m *BalanceResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type Balance struct {
	Currency             string   `protobuf:"bytes,1,opt,name=currency,proto3" json:"currency,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Total                int64    `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	Exchange             string   `protobuf:"bytes,5,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Balance) Reset()         { *m = Balance{} }
func (m *Balance) String() string { return proto.CompactTextString(m) }
func (*Balance) ProtoMessage()    {}
func (*Balance) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{2}
}

func (m *Balance) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Balance.Unmarshal(m, b)
}
func (m *Balance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Balance.Marshal(b, m, deterministic)
}
func (m *Balance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Balance.Merge(m, src)
}
func (m *Balance) XXX_Size() int {
	return xxx_messageInfo_Balance.Size(m)
}
func (m *Balance) XXX_DiscardUnknown() {
	xxx_messageInfo_Balance.DiscardUnknown(m)
}

var xxx_messageInfo_Balance proto.InternalMessageInfo

func (m *Balance) GetCurrency() string {
	if m != nil {
		return m.Currency
	}
	return ""
}

func (m *Balance) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Balance) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Balance) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Balance) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type GroupRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupRequest) Reset()         { *m = GroupRequest{} }
func (m *GroupRequest) String() string { return proto.CompactTextString(m) }
func (*GroupRequest) ProtoMessage()    {}
func (*GroupRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{3}
}

func (m *GroupRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupRequest.Unmarshal(m, b)
}
func (m *GroupRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupRequest.Marshal(b, m, deterministic)
}
func (m *GroupRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupRequest.Merge(m, src)
}
func (m *GroupRequest) XXX_Size() int {
	return xxx_messageInfo_GroupRequest.Size(m)
}
func (m *GroupRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GroupRequest proto.InternalMessageInfo

type GroupResponse struct {
	Group                *Group   `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	Groups               []*Group `protobuf:"bytes,2,rep,name=groups,proto3" json:"groups,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=tradingAPI.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GroupResponse) Reset()         { *m = GroupResponse{} }
func (m *GroupResponse) String() string { return proto.CompactTextString(m) }
func (*GroupResponse) ProtoMessage()    {}
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{4}
}

func (m *GroupResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GroupResponse.Unmarshal(m, b)
}
func (m *GroupResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GroupResponse.Marshal(b, m, deterministic)
}
func (m *GroupResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GroupResponse.Merge(m, src)
}
func (m *GroupResponse) XXX_Size() int {
	return xxx_messageInfo_GroupResponse.Size(m)
}
func (m *GroupResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GroupResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GroupResponse proto.InternalMessageInfo

func (m *GroupResponse) GetGroup() *Group {
	if m != nil {
		return m.Group
	}
	return nil
}

func (m *GroupResponse) GetGroups() []*Group {
	if m != nil {
		return m.Groups
	}
	return nil
}

func (m *GroupResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type Group struct {
	Id                   string     `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string     `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AccountIds           []string   `protobuf:"bytes,3,rep,name=accountIds,proto3" json:"accountIds,omitempty"`
	Accounts             []*Account `protobuf:"bytes,4,rep,name=accounts,proto3" json:"accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *Group) Reset()         { *m = Group{} }
func (m *Group) String() string { return proto.CompactTextString(m) }
func (*Group) ProtoMessage()    {}
func (*Group) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{5}
}

func (m *Group) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Group.Unmarshal(m, b)
}
func (m *Group) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Group.Marshal(b, m, deterministic)
}
func (m *Group) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Group.Merge(m, src)
}
func (m *Group) XXX_Size() int {
	return xxx_messageInfo_Group.Size(m)
}
func (m *Group) XXX_DiscardUnknown() {
	xxx_messageInfo_Group.DiscardUnknown(m)
}

var xxx_messageInfo_Group proto.InternalMessageInfo

func (m *Group) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Group) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Group) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

func (m *Group) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type AccountRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountRequest) Reset()         { *m = AccountRequest{} }
func (m *AccountRequest) String() string { return proto.CompactTextString(m) }
func (*AccountRequest) ProtoMessage()    {}
func (*AccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{6}
}

func (m *AccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountRequest.Unmarshal(m, b)
}
func (m *AccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountRequest.Marshal(b, m, deterministic)
}
func (m *AccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountRequest.Merge(m, src)
}
func (m *AccountRequest) XXX_Size() int {
	return xxx_messageInfo_AccountRequest.Size(m)
}
func (m *AccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AccountRequest proto.InternalMessageInfo

type AccountResponse struct {
	Account              *Account   `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`
	Accounts             []*Account `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Status               Status     `protobuf:"varint,3,opt,name=status,proto3,enum=tradingAPI.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountResponse) Reset()         { *m = AccountResponse{} }
func (m *AccountResponse) String() string { return proto.CompactTextString(m) }
func (*AccountResponse) ProtoMessage()    {}
func (*AccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{7}
}

func (m *AccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountResponse.Unmarshal(m, b)
}
func (m *AccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountResponse.Marshal(b, m, deterministic)
}
func (m *AccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountResponse.Merge(m, src)
}
func (m *AccountResponse) XXX_Size() int {
	return xxx_messageInfo_AccountResponse.Size(m)
}
func (m *AccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AccountResponse proto.InternalMessageInfo

func (m *AccountResponse) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

func (m *AccountResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

func (m *AccountResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type Account struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string            `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Exchange             string            `protobuf:"bytes,3,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Credentials          map[string]string `protobuf:"bytes,4,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{8}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Account) GetCredentials() map[string]string {
	if m != nil {
		return m.Credentials
	}
	return nil
}

type NewOrder struct {
	Pair                 string   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Amount               int64    `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Price                int64    `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Direction            string   `protobuf:"bytes,4,opt,name=direction,proto3" json:"direction,omitempty"`
	Type                 string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Context              string   `protobuf:"bytes,6,opt,name=context,proto3" json:"context,omitempty"`
	AccountIds           []string `protobuf:"bytes,7,rep,name=accountIds,proto3" json:"accountIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewOrder) Reset()         { *m = NewOrder{} }
func (m *NewOrder) String() string { return proto.CompactTextString(m) }
func (*NewOrder) ProtoMessage()    {}
func (*NewOrder) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{9}
}

func (m *NewOrder) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewOrder.Unmarshal(m, b)
}
func (m *NewOrder) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewOrder.Marshal(b, m, deterministic)
}
func (m *NewOrder) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewOrder.Merge(m, src)
}
func (m *NewOrder) XXX_Size() int {
	return xxx_messageInfo_NewOrder.Size(m)
}
func (m *NewOrder) XXX_DiscardUnknown() {
	xxx_messageInfo_NewOrder.DiscardUnknown(m)
}

var xxx_messageInfo_NewOrder proto.InternalMessageInfo

func (m *NewOrder) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *NewOrder) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *NewOrder) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *NewOrder) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *NewOrder) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *NewOrder) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *NewOrder) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

type OrderRequest struct {
	AccountIds           []string `protobuf:"bytes,1,rep,name=accountIds,proto3" json:"accountIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderRequest) Reset()         { *m = OrderRequest{} }
func (m *OrderRequest) String() string { return proto.CompactTextString(m) }
func (*OrderRequest) ProtoMessage()    {}
func (*OrderRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{10}
}

func (m *OrderRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderRequest.Unmarshal(m, b)
}
func (m *OrderRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderRequest.Marshal(b, m, deterministic)
}
func (m *OrderRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderRequest.Merge(m, src)
}
func (m *OrderRequest) XXX_Size() int {
	return xxx_messageInfo_OrderRequest.Size(m)
}
func (m *OrderRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OrderRequest proto.InternalMessageInfo

func (m *OrderRequest) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

type OrderResponse struct {
	Order                *Order   `protobuf:"bytes,1,opt,name=order,proto3" json:"order,omitempty"`
	Orders               []*Order `protobuf:"bytes,2,rep,name=orders,proto3" json:"orders,omitempty"`
	Status               Status   `protobuf:"varint,3,opt,name=status,proto3,enum=tradingAPI.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OrderResponse) Reset()         { *m = OrderResponse{} }
func (m *OrderResponse) String() string { return proto.CompactTextString(m) }
func (*OrderResponse) ProtoMessage()    {}
func (*OrderResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{11}
}

func (m *OrderResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OrderResponse.Unmarshal(m, b)
}
func (m *OrderResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OrderResponse.Marshal(b, m, deterministic)
}
func (m *OrderResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OrderResponse.Merge(m, src)
}
func (m *OrderResponse) XXX_Size() int {
	return xxx_messageInfo_OrderResponse.Size(m)
}
func (m *OrderResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OrderResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OrderResponse proto.InternalMessageInfo

func (m *OrderResponse) GetOrder() *Order {
	if m != nil {
		return m.Order
	}
	return nil
}

func (m *OrderResponse) GetOrders() []*Order {
	if m != nil {
		return m.Orders
	}
	return nil
}

func (m *OrderResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type Order struct {
	Id                    string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId            string   `protobuf:"bytes,2,opt,name=externalId,proto3" json:"externalId,omitempty"`
	Direction             string   `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	Context               string   `protobuf:"bytes,4,opt,name=context,proto3" json:"context,omitempty"`
	Type                  string   `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Pair                  string   `protobuf:"bytes,6,opt,name=pair,proto3" json:"pair,omitempty"`
	OriginalAmount        int64    `protobuf:"varint,7,opt,name=originalAmount,proto3" json:"originalAmount,omitempty"`
	RemainingAmount       int64    `protobuf:"varint,8,opt,name=remainingAmount,proto3" json:"remainingAmount,omitempty"`
	Price                 int64    `protobuf:"varint,9,opt,name=price,proto3" json:"price,omitempty"`
	AverageExecutionPrice int64    `protobuf:"varint,10,opt,name=averageExecutionPrice,proto3" json:"averageExecutionPrice,omitempty"`
	OpenedAt              int64    `protobuf:"varint,11,opt,name=openedAt,proto3" json:"openedAt,omitempty"`
	UpdatedAt             int64    `protobuf:"varint,12,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	CanceledAt            int64    `protobuf:"varint,13,opt,name=canceledAt,proto3" json:"canceledAt,omitempty"`
	AccountId             string   `protobuf:"bytes,14,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Status                string   `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`
	Exchange              string   `protobuf:"bytes,16,opt,name=exchange,proto3" json:"exchange,omitempty"`
	XXX_NoUnkeyedLiteral  struct{} `json:"-"`
	XXX_unrecognized      []byte   `json:"-"`
	XXX_sizecache         int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{12}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Order) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Order) GetDirection() string {
	if m != nil {
		return m.Direction
	}
	return ""
}

func (m *Order) GetContext() string {
	if m != nil {
		return m.Context
	}
	return ""
}

func (m *Order) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Order) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Order) GetOriginalAmount() int64 {
	if m != nil {
		return m.OriginalAmount
	}
	return 0
}

func (m *Order) GetRemainingAmount() int64 {
	if m != nil {
		return m.RemainingAmount
	}
	return 0
}

func (m *Order) GetPrice() int64 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *Order) GetAverageExecutionPrice() int64 {
	if m != nil {
		return m.AverageExecutionPrice
	}
	return 0
}

func (m *Order) GetOpenedAt() int64 {
	if m != nil {
		return m.OpenedAt
	}
	return 0
}

func (m *Order) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

func (m *Order) GetCanceledAt() int64 {
	if m != nil {
		return m.CanceledAt
	}
	return 0
}

func (m *Order) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Order) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Order) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

type Position struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ExternalId           string   `protobuf:"bytes,2,opt,name=externalId,proto3" json:"externalId,omitempty"`
	AccountId            string   `protobuf:"bytes,3,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Exchange             string   `protobuf:"bytes,4,opt,name=exchange,proto3" json:"exchange,omitempty"`
	Pair                 string   `protobuf:"bytes,5,opt,name=pair,proto3" json:"pair,omitempty"`
	Status               string   `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Amount               int64    `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	BasePrice            int64    `protobuf:"varint,8,opt,name=basePrice,proto3" json:"basePrice,omitempty"`
	MarginFunding        float64  `protobuf:"fixed64,9,opt,name=marginFunding,proto3" json:"marginFunding,omitempty"`
	MarginFundingType    int64    `protobuf:"varint,10,opt,name=marginFundingType,proto3" json:"marginFundingType,omitempty"`
	ProfitLoss           int64    `protobuf:"varint,11,opt,name=profitLoss,proto3" json:"profitLoss,omitempty"`
	ProfitLossPercentage float64  `protobuf:"fixed64,12,opt,name=profitLossPercentage,proto3" json:"profitLossPercentage,omitempty"`
	CreatedAt            int64    `protobuf:"varint,13,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
	UpdatedAt            int64    `protobuf:"varint,14,opt,name=updatedAt,proto3" json:"updatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{13}
}

func (m *Position) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Position.Unmarshal(m, b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Position.Marshal(b, m, deterministic)
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return xxx_messageInfo_Position.Size(m)
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Position) GetExternalId() string {
	if m != nil {
		return m.ExternalId
	}
	return ""
}

func (m *Position) GetAccountId() string {
	if m != nil {
		return m.AccountId
	}
	return ""
}

func (m *Position) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *Position) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Position) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *Position) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *Position) GetBasePrice() int64 {
	if m != nil {
		return m.BasePrice
	}
	return 0
}

func (m *Position) GetMarginFunding() float64 {
	if m != nil {
		return m.MarginFunding
	}
	return 0
}

func (m *Position) GetMarginFundingType() int64 {
	if m != nil {
		return m.MarginFundingType
	}
	return 0
}

func (m *Position) GetProfitLoss() int64 {
	if m != nil {
		return m.ProfitLoss
	}
	return 0
}

func (m *Position) GetProfitLossPercentage() float64 {
	if m != nil {
		return m.ProfitLossPercentage
	}
	return 0
}

func (m *Position) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Position) GetUpdatedAt() int64 {
	if m != nil {
		return m.UpdatedAt
	}
	return 0
}

type PositionResponse struct {
	Position             *Position   `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	Positions            []*Position `protobuf:"bytes,2,rep,name=positions,proto3" json:"positions,omitempty"`
	Status               Status      `protobuf:"varint,3,opt,name=status,proto3,enum=tradingAPI.Status" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PositionResponse) Reset()         { *m = PositionResponse{} }
func (m *PositionResponse) String() string { return proto.CompactTextString(m) }
func (*PositionResponse) ProtoMessage()    {}
func (*PositionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{14}
}

func (m *PositionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionResponse.Unmarshal(m, b)
}
func (m *PositionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionResponse.Marshal(b, m, deterministic)
}
func (m *PositionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionResponse.Merge(m, src)
}
func (m *PositionResponse) XXX_Size() int {
	return xxx_messageInfo_PositionResponse.Size(m)
}
func (m *PositionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PositionResponse proto.InternalMessageInfo

func (m *PositionResponse) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

func (m *PositionResponse) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *PositionResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

type PositionRequest struct {
	AccountIds           []string `protobuf:"bytes,1,rep,name=accountIds,proto3" json:"accountIds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PositionRequest) Reset()         { *m = PositionRequest{} }
func (m *PositionRequest) String() string { return proto.CompactTextString(m) }
func (*PositionRequest) ProtoMessage()    {}
func (*PositionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9108b847141e7d76, []int{15}
}

func (m *PositionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PositionRequest.Unmarshal(m, b)
}
func (m *PositionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PositionRequest.Marshal(b, m, deterministic)
}
func (m *PositionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionRequest.Merge(m, src)
}
func (m *PositionRequest) XXX_Size() int {
	return xxx_messageInfo_PositionRequest.Size(m)
}
func (m *PositionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PositionRequest proto.InternalMessageInfo

func (m *PositionRequest) GetAccountIds() []string {
	if m != nil {
		return m.AccountIds
	}
	return nil
}

func init() {
	proto.RegisterEnum("tradingAPI.Status", Status_name, Status_value)
	proto.RegisterType((*BalanceRequest)(nil), "tradingAPI.BalanceRequest")
	proto.RegisterType((*BalanceResponse)(nil), "tradingAPI.BalanceResponse")
	proto.RegisterType((*Balance)(nil), "tradingAPI.Balance")
	proto.RegisterType((*GroupRequest)(nil), "tradingAPI.GroupRequest")
	proto.RegisterType((*GroupResponse)(nil), "tradingAPI.GroupResponse")
	proto.RegisterType((*Group)(nil), "tradingAPI.Group")
	proto.RegisterType((*AccountRequest)(nil), "tradingAPI.AccountRequest")
	proto.RegisterType((*AccountResponse)(nil), "tradingAPI.AccountResponse")
	proto.RegisterType((*Account)(nil), "tradingAPI.Account")
	proto.RegisterMapType((map[string]string)(nil), "tradingAPI.Account.CredentialsEntry")
	proto.RegisterType((*NewOrder)(nil), "tradingAPI.NewOrder")
	proto.RegisterType((*OrderRequest)(nil), "tradingAPI.OrderRequest")
	proto.RegisterType((*OrderResponse)(nil), "tradingAPI.OrderResponse")
	proto.RegisterType((*Order)(nil), "tradingAPI.Order")
	proto.RegisterType((*Position)(nil), "tradingAPI.Position")
	proto.RegisterType((*PositionResponse)(nil), "tradingAPI.PositionResponse")
	proto.RegisterType((*PositionRequest)(nil), "tradingAPI.PositionRequest")
}

func init() { proto.RegisterFile("api/proto/trading.proto", fileDescriptor_9108b847141e7d76) }

var fileDescriptor_9108b847141e7d76 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x6e, 0xe3, 0x44,
	0x14, 0xc6, 0x71, 0xf3, 0xe3, 0x93, 0x34, 0xf5, 0x0e, 0xcb, 0x62, 0xb2, 0xd5, 0xaa, 0x8a, 0x56,
	0x10, 0x56, 0x90, 0x42, 0xe0, 0x02, 0x71, 0xb1, 0x22, 0xdb, 0xa6, 0x51, 0xc4, 0xaa, 0x89, 0xdc,
	0xb2, 0xb7, 0xd5, 0xd4, 0x1e, 0x82, 0x45, 0x6a, 0x9b, 0xf1, 0xa4, 0xb4, 0x12, 0x2f, 0xc0, 0x15,
	0x4f, 0xc0, 0x1d, 0xf7, 0xdc, 0x22, 0xde, 0x82, 0x47, 0xe0, 0x4d, 0xd0, 0xfc, 0xf9, 0xaf, 0x03,
	0x6a, 0xb9, 0x9b, 0x73, 0xce, 0x37, 0x33, 0x67, 0xbe, 0xf3, 0x9d, 0x19, 0x1b, 0xde, 0xc5, 0x69,
	0x74, 0x98, 0xd2, 0x84, 0x25, 0x87, 0x8c, 0xe2, 0x30, 0x8a, 0xd7, 0x63, 0x61, 0x21, 0x50, 0xe6,
	0x74, 0xb5, 0x18, 0x86, 0xd0, 0x7f, 0x85, 0x37, 0x38, 0x0e, 0x88, 0x4f, 0x7e, 0xd8, 0x92, 0x8c,
	0xa1, 0x67, 0x00, 0x38, 0x08, 0x92, 0x6d, 0xcc, 0x16, 0x61, 0xe6, 0x59, 0x07, 0xf6, 0xc8, 0xf1,
	0x4b, 0x1e, 0xf4, 0x18, 0x9a, 0x31, 0xbe, 0x22, 0x99, 0xd7, 0x10, 0x21, 0x69, 0xa0, 0x7d, 0x70,
	0xc8, 0x4d, 0xf0, 0x1d, 0x8e, 0xd7, 0x24, 0xf3, 0x6c, 0x11, 0x29, 0x1c, 0xc3, 0x5f, 0x2d, 0xd8,
	0xcb, 0xb7, 0xc9, 0xd2, 0x24, 0xce, 0x08, 0xfa, 0x18, 0xda, 0x97, 0xd2, 0xe5, 0x59, 0x07, 0xd6,
	0xa8, 0x3b, 0x79, 0x7b, 0x5c, 0xe4, 0x35, 0xd6, 0x68, 0x8d, 0x41, 0x87, 0xd0, 0x51, 0x43, 0xb9,
	0xf3, 0xbf, 0xe0, 0x73, 0x10, 0x7a, 0x01, 0xad, 0x8c, 0x61, 0xb6, 0xe5, 0xe9, 0x58, 0xa3, 0xfe,
	0x04, 0x95, 0xe1, 0x67, 0x22, 0xe2, 0x2b, 0xc4, 0xf0, 0x67, 0x0b, 0xda, 0x6a, 0x05, 0x34, 0x80,
	0x4e, 0xb0, 0xa5, 0x94, 0xc4, 0xc1, 0xad, 0x48, 0xcc, 0xf1, 0x73, 0x1b, 0x21, 0xd8, 0xe1, 0xc7,
	0xf5, 0x1a, 0xc2, 0x2f, 0xc6, 0xfc, 0xe4, 0x39, 0x3b, 0x62, 0x2b, 0xc7, 0x2f, 0x1c, 0x9c, 0x2d,
	0x96, 0x30, 0xbc, 0xf1, 0x76, 0x0e, 0xac, 0x91, 0xed, 0x4b, 0x83, 0xef, 0xa1, 0xc9, 0xf1, 0x9a,
	0x72, 0x0f, 0x6d, 0x0f, 0xfb, 0xd0, 0x9b, 0xd3, 0x64, 0x9b, 0xaa, 0x7a, 0x0c, 0x7f, 0xb1, 0x60,
	0x57, 0x39, 0x14, 0x73, 0x1f, 0x40, 0x73, 0xcd, 0x1d, 0x8a, 0xb7, 0x47, 0xe5, 0x83, 0x49, 0xa4,
	0x8c, 0xa3, 0x0f, 0xa1, 0x25, 0x06, 0x9a, 0x31, 0x03, 0x52, 0x01, 0x1e, 0xc4, 0xd6, 0x4f, 0xd0,
	0x14, 0x93, 0x51, 0x1f, 0x1a, 0x51, 0xa8, 0x48, 0x6a, 0x44, 0xa1, 0x91, 0x9e, 0xaa, 0x9c, 0xec,
	0x3b, 0x72, 0x3a, 0x84, 0x8e, 0xb2, 0x32, 0x6f, 0xe7, 0x6e, 0x5d, 0xa7, 0x32, 0xe6, 0xe7, 0xa0,
	0xa1, 0x0b, 0x7d, 0xed, 0x54, 0x0c, 0x71, 0x75, 0xe5, 0xae, 0x42, 0x5d, 0x6a, 0x86, 0x49, 0x5d,
	0x1a, 0xad, 0x31, 0x95, 0x2c, 0x1a, 0xf7, 0xc8, 0xe2, 0x41, 0x7c, 0xfd, 0x65, 0x41, 0x5b, 0xad,
	0x70, 0x2f, 0xca, 0xca, 0xea, 0xb0, 0xab, 0xea, 0x40, 0x27, 0xd0, 0x0d, 0x28, 0x09, 0x49, 0xcc,
	0x22, 0xbc, 0xd1, 0x8c, 0x3d, 0x37, 0xe4, 0x3a, 0x3e, 0x2a, 0x60, 0xb3, 0x98, 0xd1, 0x5b, 0xbf,
	0x3c, 0x71, 0xf0, 0x12, 0xdc, 0x3a, 0x00, 0xb9, 0x60, 0x7f, 0x4f, 0xb4, 0xe8, 0xf9, 0x90, 0xab,
	0xf7, 0x1a, 0x6f, 0xb6, 0x3a, 0x3d, 0x69, 0x7c, 0xd9, 0xf8, 0xc2, 0x1a, 0xfe, 0x61, 0x41, 0xe7,
	0x94, 0xfc, 0xb8, 0xa4, 0x21, 0xa1, 0xfc, 0x10, 0x29, 0x8e, 0xa8, 0x9a, 0x29, 0xc6, 0xe8, 0x09,
	0xb4, 0xf0, 0x95, 0xe0, 0xbf, 0x21, 0x94, 0xaf, 0x2c, 0xbe, 0x64, 0x4a, 0xa3, 0x40, 0x9e, 0xcc,
	0xf6, 0xa5, 0xc1, 0x9b, 0x28, 0x8c, 0x28, 0x09, 0x58, 0x94, 0xc4, 0xa2, 0x55, 0x1c, 0xbf, 0x70,
	0xf0, 0xf5, 0xd9, 0x6d, 0xaa, 0x5b, 0x45, 0x8c, 0x91, 0x07, 0xed, 0x20, 0x89, 0x19, 0xb9, 0x61,
	0x5e, 0x4b, 0xb8, 0xb5, 0x59, 0x53, 0x5c, 0xbb, 0xae, 0xb8, 0xe1, 0x18, 0x7a, 0x22, 0xed, 0x7b,
	0x5e, 0x78, 0xa2, 0x01, 0xd5, 0x84, 0xa2, 0x01, 0x13, 0xee, 0x30, 0x35, 0xa0, 0x44, 0xca, 0x38,
	0x6f, 0x40, 0x31, 0x30, 0x36, 0xa0, 0x44, 0x2a, 0xc0, 0x83, 0x04, 0xf5, 0xb7, 0x0d, 0x4d, 0xc9,
	0x7c, 0x5d, 0x4e, 0xcf, 0x00, 0xc8, 0x0d, 0x23, 0x34, 0xc6, 0x9b, 0x45, 0xa8, 0xaa, 0x56, 0xf2,
	0x54, 0x79, 0xb6, 0xeb, 0x3c, 0x97, 0x38, 0xdd, 0xa9, 0x72, 0x6a, 0xaa, 0x80, 0xae, 0x7a, 0xab,
	0x54, 0xf5, 0xf7, 0xa1, 0x9f, 0xd0, 0x68, 0x1d, 0xc5, 0x78, 0x33, 0x95, 0xd5, 0x6f, 0x8b, 0x32,
	0xd7, 0xbc, 0x68, 0x04, 0x7b, 0x94, 0x5c, 0xe1, 0x28, 0xe6, 0x07, 0x94, 0xc0, 0x8e, 0x00, 0xd6,
	0xdd, 0x85, 0x5e, 0x9c, 0xb2, 0x5e, 0x3e, 0x87, 0x77, 0xf0, 0x35, 0xa1, 0x78, 0x4d, 0x66, 0x37,
	0x24, 0xd8, 0xf2, 0xec, 0x57, 0x02, 0x05, 0x02, 0x65, 0x0e, 0xf2, 0xc6, 0x4a, 0x52, 0x12, 0x93,
	0x70, 0xca, 0xbc, 0xae, 0x00, 0xe6, 0x36, 0x67, 0x66, 0x9b, 0x86, 0x98, 0x89, 0x60, 0x4f, 0x04,
	0x0b, 0x07, 0xe7, 0x35, 0xe0, 0xaf, 0xc3, 0x46, 0x84, 0x77, 0x45, 0xb8, 0xe4, 0xa9, 0x3e, 0x02,
	0xfd, 0xfa, 0x23, 0xf0, 0x24, 0xaf, 0xed, 0x9e, 0x08, 0x29, 0xab, 0xd2, 0xe8, 0x6e, 0xed, 0x19,
	0xf8, 0xd3, 0x86, 0xce, 0x2a, 0xc9, 0x22, 0x51, 0x98, 0xff, 0x51, 0xe6, 0xff, 0x78, 0x93, 0xca,
	0xdb, 0xee, 0xd4, 0xee, 0x17, 0x5d, 0xd4, 0x66, 0xb5, 0x95, 0x55, 0xfa, 0xad, 0x4a, 0xfa, 0x45,
	0x8b, 0xb7, 0x2b, 0x2d, 0xbe, 0x0f, 0xce, 0x25, 0xce, 0x88, 0x2c, 0x88, 0x2c, 0x6b, 0xe1, 0x40,
	0xcf, 0x61, 0xf7, 0x0a, 0xd3, 0x75, 0x14, 0x9f, 0x6c, 0x63, 0xae, 0x6f, 0x51, 0x58, 0xcb, 0xaf,
	0x3a, 0xd1, 0x47, 0xf0, 0xa8, 0xe2, 0x38, 0xe7, 0xea, 0x93, 0xc5, 0xbd, 0x1b, 0xe0, 0x7c, 0xa4,
	0x34, 0xf9, 0x36, 0x62, 0xaf, 0x93, 0x2c, 0x53, 0xa5, 0x2d, 0x79, 0xd0, 0x04, 0x1e, 0x17, 0xd6,
	0x8a, 0xd0, 0x80, 0xc4, 0x0c, 0xaf, 0x89, 0xa8, 0xb3, 0xe5, 0x1b, 0x63, 0xfc, 0x14, 0x01, 0x25,
	0x4a, 0x10, 0xb2, 0xe2, 0x85, 0xa3, 0x2a, 0x97, 0x7e, 0x4d, 0x2e, 0xc3, 0xdf, 0x2c, 0x70, 0x75,
	0xf1, 0xf2, 0x5b, 0xe3, 0x13, 0xe8, 0xa4, 0xca, 0xa7, 0x2e, 0x8e, 0xc7, 0xe5, 0x1e, 0xcf, 0xf1,
	0x39, 0x0a, 0x4d, 0xc0, 0xd1, 0x63, 0x7d, 0x83, 0x98, 0xa7, 0x14, 0xb0, 0x07, 0xdd, 0x23, 0x9f,
	0xc2, 0x5e, 0x91, 0xe5, 0xbd, 0x2e, 0xc3, 0x17, 0x47, 0xd0, 0x92, 0x8b, 0xa0, 0x16, 0x34, 0x96,
	0x5f, 0xbb, 0x6f, 0xa1, 0x5d, 0x70, 0x4e, 0x97, 0xe7, 0x17, 0x27, 0xcb, 0x6f, 0x4e, 0x8f, 0x5d,
	0x0b, 0xb9, 0xd0, 0x5b, 0x9c, 0xbe, 0x99, 0xbe, 0x5e, 0x1c, 0x5f, 0x1c, 0x4f, 0xcf, 0xa7, 0x6e,
	0x83, 0x7b, 0xce, 0x66, 0xfe, 0x9b, 0x99, 0x7f, 0x31, 0xf3, 0xfd, 0xa5, 0xef, 0xda, 0x93, 0xdf,
	0x6d, 0xe8, 0x9f, 0xcb, 0xac, 0xce, 0x08, 0xbd, 0xe6, 0xaa, 0x38, 0x81, 0xee, 0x9c, 0xb0, 0xa9,
	0x7e, 0x5e, 0x07, 0xa6, 0xd7, 0x57, 0xa6, 0x38, 0x78, 0x6a, 0x8c, 0x29, 0x92, 0xbf, 0x02, 0x67,
	0x4e, 0xd8, 0x5c, 0x7e, 0xd4, 0x78, 0x77, 0xbf, 0x77, 0xd4, 0x1a, 0xef, 0x19, 0x22, 0x6a, 0x05,
	0x99, 0xc9, 0x2b, 0xfd, 0x19, 0x39, 0x30, 0x7d, 0x65, 0x9a, 0x32, 0xa9, 0x7f, 0xdf, 0x2e, 0xa0,
	0x37, 0x27, 0x6c, 0x95, 0x17, 0xe6, 0xa9, 0xb1, 0x72, 0x6a, 0xa5, 0x7d, 0x73, 0x50, 0x2d, 0xf5,
	0x12, 0xba, 0x47, 0x42, 0x79, 0xf2, 0xd2, 0xaf, 0x68, 0x40, 0x3f, 0xc2, 0xd5, 0x23, 0x55, 0xdf,
	0x2b, 0x49, 0xca, 0x52, 0x3e, 0x34, 0x9e, 0x01, 0x67, 0x20, 0xa5, 0xb2, 0xc2, 0x65, 0x4b, 0xfc,
	0x39, 0x7c, 0xf6, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x18, 0xb1, 0x30, 0xc2, 0x54, 0x0c, 0x00,
	0x00,
}
